siteName: Svelte ID
siteUrl: https://svelteid.netlify.app
description: Svelte ID adalah komunitas untuk para pengembang web yang menggunakan atau sedang belajar kerangka kerja Svelte. Kami mengadakan meetup dua bulan sekali dan siapa pun boleh menjadi pembicaranya. Svelte ID juga menjadi ajang bagi para anggotanya untuk saling bertukar informasi terkait Svelte ataupun pengembangan web.
keywords:
  - website
  - komunitas
